kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: caddy-pvc
  namespace: MY-WOKSPACE
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: caddy-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
